SELECT CLASSES.CLASS AS SHIP_NAME,
 	   CLASSES.COUNTRY, 
 	   CLASSES.NUMGUNS, 
 	   SHIPS.LAUNCHED
  FROM CLASSES -- OR LEFT OUTER JOIN IF WE WANT THE SHIPS WITH NULL LAUNCHED(LIKE Bismarck) --
 	   JOIN SHIPS
	   ON SHIPS.CLASS = CLASSES.CLASS;

SELECT CLASSES.CLASS AS SHIP_NAME,
	   CLASSES.COUNTRY,  
	   CLASSES.NUMGUNS,
	   SHIPS.LAUNCHED
  FROM CLASSES
	   LEFT JOIN SHIPS
       ON SHIPS.CLASS = CLASSES.CLASS;

SELECT OUTCOMES.SHIP
  FROM OUTCOMES
       JOIN BATTLES
       ON BATTLES.NAME = OUTCOMES.BATTLE
 WHERE BATTLES.DATE LIKE '1942%';

SELECT CLASSES.COUNTRY, SHIPS.NAME
  FROM SHIPS
	   LEFT OUTER JOIN OUTCOMES
	   ON SHIPS.NAME = OUTCOMES.SHIP
	   JOIN CLASSES  -- SAME AS LEFT JOIN IN THIS CASE --
	   ON CLASSES.CLASS = SHIPS.CLASS -- THE SAME WITHOUT ON --
 WHERE OUTCOMES.BATTLE IS NULL
 ORDER BY CLASSES.COUNTRY;